### ISSUE TITLE
About your paper.

### ISSUE THREAD

**Issue by kk6398** [wxxxxxxh/AMAF-Net#1]
I want to read your paper in detail. Could you provide your paper please?

**Comment by wxxxxxxh** [comment]
Hi~
Sorry for my late reply.
There is no regular paper. You can refer to [1] for details about my method (Team Name: Summer).
Thanks for you attention on my work.

[1] AIM 2020 challenge on efficient super-resolution: Methods and results

**Comment by wxxxxxxh** [comment]
> I want to read your paper in detail. Could you provide your paper please?

Hi~
Sorry for my late reply.
There is no regular paper. You can refer to [1] for details about my method (Team Name: Summer).
Thanks for you attention on my work.

[1] AIM 2020 challenge on efficient super-resolution: Methods and results

**Comment by kk6398** [comment]
Thank you for your reply.
